version: '3'
services:
  magic-link:
    container_name: magic-link
    image: magic-link:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '4001:4001'
      - '4040:4040'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      magic-net:
        ipv4_address: 180.29.1.3

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: magiclink
      MYSQL_USER: magicroot
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - database:/var/lib/mysql
    networks:
      magic-net:
        ipv4_address: 180.29.1.2

volumes:
  database:

networks:
  magic-net:
    ipam:
      driver: default
      config:
        - subnet: 180.29.0.0/16
